name: Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Pull the change from server
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        run: | 
          cat /etc/os-release
          ls -l
          cd /var/www/html/actiontest
          git pull
          echo $USERNAME
          echo $TOKEN
