name: MyLaravel

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - name: Deploy code
      uses:
      with:
        username: "papinder"
        host: "52.66.202.105"
        password: "papinder@123*"
        script: cd /var/www/html && ./server_deploy.sh
