name: MyLaravel

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy code
      uses: appleboy/ssh-action@master
      with:
        username: 'papinder'
        host: '52.66.202.105'
        password: 'papinder@123*'
        script: 'cd /var/www/html/actiontest/ && git pull'
