name: MyLaravel

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy code
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SSH_HOST}}
        username : ${{secrets.SSH_USERNAME }} 
        password: ${{secrets.SSH_PASSWORD}}
        key: ${{secrets.SSH_KEY}}
        script: 'cd /var/www/html/actiontest/ && ./deployer.sh'
